// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	HttpScopes = "http.Scopes"
)

// Defines values for ConversationResponseStatus.
const (
	Archived   ConversationResponseStatus = "archived"
	Assigned   ConversationResponseStatus = "assigned"
	Deleted    ConversationResponseStatus = "deleted"
	Unassigned ConversationResponseStatus = "unassigned"
)

// Valid indicates whether the value is a known member of the ConversationResponseStatus enum.
func (e ConversationResponseStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Assigned:
		return true
	case Deleted:
		return true
	case Unassigned:
		return true
	default:
		return false
	}
}

// Defines values for ConversationResponseStatusCategory.
const (
	Open     ConversationResponseStatusCategory = "open"
	Resolved ConversationResponseStatusCategory = "resolved"
	Waiting  ConversationResponseStatusCategory = "waiting"
)

// Valid indicates whether the value is a known member of the ConversationResponseStatusCategory enum.
func (e ConversationResponseStatusCategory) Valid() bool {
	switch e {
	case Open:
		return true
	case Resolved:
		return true
	case Waiting:
		return true
	default:
		return false
	}
}

// Defines values for MessageResponseDraftMode.
const (
	Private MessageResponseDraftMode = "private"
	Shared  MessageResponseDraftMode = "shared"
)

// Valid indicates whether the value is a known member of the MessageResponseDraftMode enum.
func (e MessageResponseDraftMode) Valid() bool {
	switch e {
	case Private:
		return true
	case Shared:
		return true
	default:
		return false
	}
}

// Defines values for MessageResponseType.
const (
	Call       MessageResponseType = "call"
	Custom     MessageResponseType = "custom"
	Email      MessageResponseType = "email"
	Facebook   MessageResponseType = "facebook"
	FrontChat  MessageResponseType = "front_chat"
	Googleplay MessageResponseType = "googleplay"
	Intercom   MessageResponseType = "intercom"
	Internal   MessageResponseType = "internal"
	PhoneCall  MessageResponseType = "phone-call"
	Sms        MessageResponseType = "sms"
	Tweet      MessageResponseType = "tweet"
	TweetDm    MessageResponseType = "tweet_dm"
	Whatsapp   MessageResponseType = "whatsapp"
	YaloWha    MessageResponseType = "yalo_wha"
)

// Valid indicates whether the value is a known member of the MessageResponseType enum.
func (e MessageResponseType) Valid() bool {
	switch e {
	case Call:
		return true
	case Custom:
		return true
	case Email:
		return true
	case Facebook:
		return true
	case FrontChat:
		return true
	case Googleplay:
		return true
	case Intercom:
		return true
	case Internal:
		return true
	case PhoneCall:
		return true
	case Sms:
		return true
	case Tweet:
		return true
	case TweetDm:
		return true
	case Whatsapp:
		return true
	case YaloWha:
		return true
	default:
		return false
	}
}

// Defines values for RecipientResponseRole.
const (
	Bcc     RecipientResponseRole = "bcc"
	Cc      RecipientResponseRole = "cc"
	From    RecipientResponseRole = "from"
	ReplyTo RecipientResponseRole = "reply-to"
	To      RecipientResponseRole = "to"
)

// Valid indicates whether the value is a known member of the RecipientResponseRole enum.
func (e RecipientResponseRole) Valid() bool {
	switch e {
	case Bcc:
		return true
	case Cc:
		return true
	case From:
		return true
	case ReplyTo:
		return true
	case To:
		return true
	default:
		return false
	}
}

// Defines values for TeammateResponseType.
const (
	API         TeammateResponseType = "API"
	CSAT        TeammateResponseType = "CSAT"
	Integration TeammateResponseType = "integration"
	Macro       TeammateResponseType = "macro"
	Rule        TeammateResponseType = "rule"
	User        TeammateResponseType = "user"
	Visitor     TeammateResponseType = "visitor"
)

// Valid indicates whether the value is a known member of the TeammateResponseType enum.
func (e TeammateResponseType) Valid() bool {
	switch e {
	case API:
		return true
	case CSAT:
		return true
	case Integration:
		return true
	case Macro:
		return true
	case Rule:
		return true
	case User:
		return true
	case Visitor:
		return true
	default:
		return false
	}
}

// Defines values for SortOrder.
const (
	SortOrderAsc  SortOrder = "asc"
	SortOrderDesc SortOrder = "desc"
)

// Valid indicates whether the value is a known member of the SortOrder enum.
func (e SortOrder) Valid() bool {
	switch e {
	case SortOrderAsc:
		return true
	case SortOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListConversationMessagesParamsSortOrder.
const (
	ListConversationMessagesParamsSortOrderAsc  ListConversationMessagesParamsSortOrder = "asc"
	ListConversationMessagesParamsSortOrderDesc ListConversationMessagesParamsSortOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListConversationMessagesParamsSortOrder enum.
func (e ListConversationMessagesParamsSortOrder) Valid() bool {
	switch e {
	case ListConversationMessagesParamsSortOrderAsc:
		return true
	case ListConversationMessagesParamsSortOrderDesc:
		return true
	default:
		return false
	}
}

// Attachment defines model for Attachment.
type Attachment struct {
	// ContentType Content type of the attached file in [MIME format](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types). Note that some attachments types may not be supported.
	ContentType string `json:"content_type"`

	// Filename Name of the attached file
	Filename string `json:"filename"`

	// Id The unique identifier of the attachment.
	Id string `json:"id"`

	// Metadata Attachment metadata
	Metadata struct {
		// Cid Unique identifier used to link an attachment to where it is used in the message body
		Cid *string `json:"cid,omitempty"`

		// IsInline Whether or not the attachment is part of the message body
		IsInline *bool `json:"is_inline,omitempty"`
	} `json:"metadata"`

	// Size Size (in byte) of the attached file
	Size int `json:"size"`

	// Url URL to download the attached file
	Url string `json:"url"`
}

// ConversationResponse defines model for ConversationResponse.
type ConversationResponse struct {
	UnderscoreLinks struct {
		Related *struct {
			// Comments Link to conversation comments
			Comments *string `json:"comments,omitempty"`

			// Events Link to conversation events
			Events *string `json:"events,omitempty"`

			// Followers Link to conversation followers
			Followers *string `json:"followers,omitempty"`

			// Inboxes Link to conversation inboxes
			Inboxes *string `json:"inboxes,omitempty"`

			// LastMessage Link to last message of the conversation
			LastMessage *string `json:"last_message,omitempty"`

			// Messages Link to conversation messages
			Messages *string `json:"messages,omitempty"`
		} `json:"related,omitempty"`

		// Self Link to resource
		Self *string `json:"self,omitempty"`
	} `json:"_links"`

	// Assignee A teammate is a user in Front.
	Assignee TeammateResponse `json:"assignee"`

	// CreatedAt Timestamp at which the conversation was created.
	CreatedAt *float32 `json:"created_at,omitempty"`

	// CustomFields An object whose key is the `name` property defined for the custom field in the Front UI. The value of the key must use the same `type` specified for the custom field, as described in https://dev.frontapp.com/reference/custom-fields
	CustomFields CustomFieldParameter `json:"custom_fields"`

	// Id Unique identifier of the conversation
	Id string `json:"id"`

	// IsPrivate Whether or not the conversation is private
	IsPrivate bool `json:"is_private"`

	// Links List of the links for this conversation
	Links []LinkResponse `json:"links"`

	// Metadata Optional metadata about the conversation
	Metadata struct {
		// ExternalConversationIds List of external_ids for partner channel associated with the conversation. Only present for partner channel token authenticated requests.
		ExternalConversationIds *[]string `json:"external_conversation_ids,omitempty"`
	} `json:"metadata"`
	Recipient RecipientResponse `json:"recipient"`

	// ScheduledReminders List of scheduled (non-expired and non-canceled) reminders for this conversation
	ScheduledReminders []Reminder `json:"scheduled_reminders"`

	// Status Status of the conversation
	Status ConversationResponseStatus `json:"status"`

	// StatusCategory Status category of the conversation
	StatusCategory *ConversationResponseStatusCategory `json:"status_category,omitempty"`

	// StatusId Unique identifier of the conversation status category, only present if ticketing is enabled
	StatusId *string `json:"status_id,omitempty"`

	// Subject Subject of the message for email message
	Subject string `json:"subject"`

	// Tags List of the tags for this conversation
	Tags []TagResponse `json:"tags"`

	// TicketIds List of ticket ids associated with the conversation
	TicketIds []string `json:"ticket_ids"`

	// UpdatedAt Timestamp at which the conversation was last updated.
	UpdatedAt *float32 `json:"updated_at,omitempty"`

	// WaitingSince Timestamp of the oldest unreplied message.
	WaitingSince *float32 `json:"waiting_since,omitempty"`
}

// ConversationResponseStatus Status of the conversation
type ConversationResponseStatus string

// ConversationResponseStatusCategory Status category of the conversation
type ConversationResponseStatusCategory string

// CustomFieldParameter An object whose key is the `name` property defined for the custom field in the Front UI. The value of the key must use the same `type` specified for the custom field, as described in https://dev.frontapp.com/reference/custom-fields
type CustomFieldParameter = map[string]interface{}

// InboxResponse defines model for InboxResponse.
type InboxResponse struct {
	UnderscoreLinks *struct {
		Related *struct {
			// Channels Link to inbox channels
			Channels *string `json:"channels,omitempty"`

			// Conversations Link to inbox conversations
			Conversations *string `json:"conversations,omitempty"`

			// Owner Link to inbox owner
			Owner *string `json:"owner,omitempty"`

			// Teammates Link to inbox teammates
			Teammates *string `json:"teammates,omitempty"`
		} `json:"related,omitempty"`

		// Self Link to resource
		Self *string `json:"self,omitempty"`
	} `json:"_links,omitempty"`

	// CustomFields An object whose key is the `name` property defined for the custom field in the Front UI. The value of the key must use the same `type` specified for the custom field, as described in https://dev.frontapp.com/reference/custom-fields
	CustomFields *CustomFieldParameter `json:"custom_fields,omitempty"`

	// Id Unique identifier for the inbox
	Id *string `json:"id,omitempty"`

	// IsPrivate Whether or not the inbox is individual
	IsPrivate *bool `json:"is_private,omitempty"`

	// IsPublic Whether or not the inbox is available to all members of a team by default
	IsPublic *bool `json:"is_public,omitempty"`

	// Name Name of the inbox
	Name *string `json:"name,omitempty"`
}

// LinkResponse A link used to connect a Front conversation to an external resource.
type LinkResponse struct {
	UnderscoreLinks struct {
		// Self Link to resource
		Self *string `json:"self,omitempty"`
	} `json:"_links"`

	// CustomFields An object whose key is the `name` property defined for the custom field in the Front UI. The value of the key must use the same `type` specified for the custom field, as described in https://dev.frontapp.com/reference/custom-fields
	CustomFields CustomFieldParameter `json:"custom_fields"`

	// ExternalUrl Underlying identifying external URL of the link
	ExternalUrl string `json:"external_url"`

	// Id Unique identifier of the link
	Id string `json:"id"`

	// Name Display name of the link
	Name string `json:"name"`

	// Type Type of the link. Typically associated with the underlying link provider (if known)
	Type string `json:"type"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	UnderscoreLinks *struct {
		Related *struct {
			// Conversation Link to message conversation
			Conversation *string `json:"conversation,omitempty"`

			// MessageRepliedTo Link to message this message replied to
			MessageRepliedTo *string `json:"message_replied_to,omitempty"`

			// MessageSeen Link to message seen information
			MessageSeen *string `json:"message_seen,omitempty"`
		} `json:"related,omitempty"`

		// Self Link to resource
		Self *string `json:"self,omitempty"`
	} `json:"_links,omitempty"`

	// Attachments List of files attached to the message
	Attachments *[]Attachment `json:"attachments,omitempty"`

	// Author A teammate is a user in Front.
	Author *TeammateResponse `json:"author,omitempty"`

	// Blurb Preview of the message body
	Blurb *string `json:"blurb,omitempty"`

	// Body Body of the message
	Body *string `json:"body,omitempty"`

	// CreatedAt The timestamp when the message was sent or received
	CreatedAt *float32 `json:"created_at,omitempty"`

	// DraftMode If the message is a draft, describes the draft mode. Can be 'private' (draft is visible to the author only) or 'shared' (draft is visible to all teammates with access to the conversation).
	DraftMode *MessageResponseDraftMode `json:"draft_mode,omitempty"`

	// ErrorType Type of the error when the draft failed to be sent
	ErrorType *string `json:"error_type,omitempty"`

	// Id Unique identifier of the message
	Id *string `json:"id,omitempty"`

	// IsInbound Whether or not the message has been received or sent
	IsInbound *bool `json:"is_inbound,omitempty"`

	// MessageUid Secondary unique identifier of a message. Generated by Front on message creation. Learn more at about the [message UID](https://dev.frontapp.com/reference/messages#creating-a-new-message).
	MessageUid *string `json:"message_uid,omitempty"`

	// Metadata Optional metadata about the message
	Metadata *struct {
		// ChatVisitorUrl For `front_chat` messages only. Source URL from the chat widget when sending a message.
		ChatVisitorUrl *string `json:"chat_visitor_url,omitempty"`

		// Duration For `truly-call` messages only. Length of the call in seconds.
		Duration *int `json:"duration,omitempty"`

		// ExternalId For `tweet` or 'custom' (partner channel token authenticated) messages only. Unique message identifier in the underlying provider (Twitter or Partner). For custom messages, only present for partner channel token authenticated requests.
		ExternalId *string `json:"external_id,omitempty"`

		// HaveBeenAnswered For `truly-call` messages only. Whether or not the call have been answered.
		HaveBeenAnswered *bool `json:"have_been_answered,omitempty"`

		// HaveBeenFavorited For `tweet` messages only. Whether or not the tweet have been favorited.
		HaveBeenFavorited *bool `json:"have_been_favorited,omitempty"`

		// HaveBeenRetweeted For `tweet` messages only. Whether or not the tweet have been retweeted.
		HaveBeenRetweeted *bool `json:"have_been_retweeted,omitempty"`

		// Headers For `custom` messages only. Custom object holding internal information.
		Headers *map[string]interface{} `json:"headers,omitempty"`

		// IntercomUrl For `intercom` messages only. URL of the Intercom conversation the message is coming from.
		IntercomUrl *string `json:"intercom_url,omitempty"`

		// IsRetweet For `tweet` messages only. Whether or not the tweet is a retweet.
		IsRetweet *bool `json:"is_retweet,omitempty"`

		// ThreadRef For `custom` messages only. Custom reference which is used to thread messages.
		ThreadRef *string `json:"thread_ref,omitempty"`

		// TwitterUrl For `tweet` messages only. URL of the tweet.
		TwitterUrl *string `json:"twitter_url,omitempty"`
	} `json:"metadata,omitempty"`
	Recipients *[]RecipientResponse `json:"recipients,omitempty"`
	Signature  *SignatureResponse   `json:"signature,omitempty"`

	// Subject Subject of the message
	Subject *string `json:"subject,omitempty"`

	// Text Text version of the body for email messages
	Text *string `json:"text,omitempty"`

	// Type Type of the message
	Type *MessageResponseType `json:"type,omitempty"`

	// Version The current version of the message in Front
	Version *string `json:"version,omitempty"`
}

// MessageResponseDraftMode If the message is a draft, describes the draft mode. Can be 'private' (draft is visible to the author only) or 'shared' (draft is visible to all teammates with access to the conversation).
type MessageResponseDraftMode string

// MessageResponseType Type of the message
type MessageResponseType string

// RecipientResponse defines model for RecipientResponse.
type RecipientResponse struct {
	UnderscoreLinks struct {
		Related *struct {
			// Contact Link to recipient contact
			Contact *string `json:"contact,omitempty"`
		} `json:"related,omitempty"`
	} `json:"_links"`

	// Handle Handle of the contact. Can be any string used to uniquely identify the contact
	Handle string `json:"handle"`

	// Name Name of the recipient.
	Name *string `json:"name"`

	// Role Role of the recipient
	Role RecipientResponseRole `json:"role"`
}

// RecipientResponseRole Role of the recipient
type RecipientResponseRole string

// Reminder defines model for Reminder.
type Reminder struct {
	UnderscoreLinks struct {
		Related *struct {
			// Owner Link to conversation owner
			Owner *string `json:"owner,omitempty"`
		} `json:"related,omitempty"`
	} `json:"_links"`

	// CreatedAt Timestamp at which the conversation reminder has been created
	CreatedAt *float32 `json:"created_at,omitempty"`

	// ScheduledAt Timestamp that the conversation reminder has been scheduled for
	ScheduledAt *float32 `json:"scheduled_at,omitempty"`

	// UpdatedAt Timestamp at which the conversation reminder has been updated
	UpdatedAt *float32 `json:"updated_at,omitempty"`
}

// SignatureResponse defines model for SignatureResponse.
type SignatureResponse struct {
	UnderscoreLinks struct {
		Related *struct {
			// Owner Link to signature's owner (either a team or teammate)
			Owner *string `json:"owner,omitempty"`
		} `json:"related,omitempty"`

		// Self Link to resource
		Self *string `json:"self,omitempty"`
	} `json:"_links"`

	// Body Body of the signature
	Body       string    `json:"body"`
	ChannelIds *[]string `json:"channel_ids"`

	// Id Unique identifier of the signature
	Id string `json:"id"`

	// IsDefault Whether the signature is the default signature for the team or teammate.
	IsDefault bool `json:"is_default"`

	// IsPrivate Whether the signature is private to the teammate.
	IsPrivate bool `json:"is_private"`

	// IsVisibleForAllTeammateChannels Whether or not the signature is available in teammate channels.
	IsVisibleForAllTeammateChannels bool `json:"is_visible_for_all_teammate_channels"`

	// Name Name of the signature
	Name *string `json:"name"`

	// SenderInfo Sender info of the signature
	SenderInfo *string `json:"sender_info"`
}

// TagResponse A tag is a label that can be used to classify conversations.
type TagResponse struct {
	UnderscoreLinks struct {
		Related *struct {
			// Children Link to tag children
			Children *string `json:"children,omitempty"`

			// Conversations Link to tag conversations
			Conversations *string `json:"conversations,omitempty"`

			// Owner Link to tag owner
			Owner *string `json:"owner,omitempty"`

			// ParentTag Link to parent tag
			ParentTag *string `json:"parent_tag,omitempty"`
		} `json:"related,omitempty"`

		// Self Link to resource
		Self *string `json:"self,omitempty"`
	} `json:"_links"`

	// CreatedAt Timestamp of tag create creation
	CreatedAt *float32 `json:"created_at,omitempty"`

	// Description Description of the tag
	Description *string `json:"description"`

	// Highlight Highlight color or emoji of the tag. Null if the tag does not have a highlight.
	Highlight *string `json:"highlight"`

	// Id Unique identifier of the tag
	Id string `json:"id"`

	// IsPrivate Whether or not the tag is individual
	IsPrivate bool `json:"is_private"`

	// IsVisibleInConversationLists Whether the tag is visible in conversation lists.
	IsVisibleInConversationLists bool `json:"is_visible_in_conversation_lists"`

	// Name Name of the tag
	Name string `json:"name"`

	// UpdatedAt Timestamp of the last tag update
	UpdatedAt *float32 `json:"updated_at,omitempty"`
}

// TeammateResponse A teammate is a user in Front.
type TeammateResponse struct {
	UnderscoreLinks struct {
		Related *struct {
			// BotSource Link to the source resource of the bot (e.g. rule)
			BotSource *string `json:"botSource,omitempty"`

			// Conversations Link to teammate's conversations
			Conversations *string `json:"conversations,omitempty"`

			// Inboxes Link to teammate's inboxes
			Inboxes *string `json:"inboxes,omitempty"`
		} `json:"related,omitempty"`

		// Self Link to resource
		Self *string `json:"self,omitempty"`
	} `json:"_links"`

	// CustomFields An object whose key is the `name` property defined for the custom field in the Front UI. The value of the key must use the same `type` specified for the custom field, as described in https://dev.frontapp.com/reference/custom-fields
	CustomFields CustomFieldParameter `json:"custom_fields"`

	// Email Email address of the teammate
	Email string `json:"email"`

	// FirstName First name of the teammate
	FirstName string `json:"first_name"`

	// Id Unique identifier of the teammate
	Id string `json:"id"`

	// IsAdmin Whether or not the teammate is an admin in your company
	IsAdmin bool `json:"is_admin"`

	// IsAvailable Whether or not the teammate is available
	IsAvailable bool `json:"is_available"`

	// IsBlocked Whether or not the teammate account has been blocked
	IsBlocked bool `json:"is_blocked"`

	// LastName Last name of the teammate
	LastName string `json:"last_name"`

	// Type Type of the teammate, normal teammates are denoted as "user", while visitors are denoted as "visitor".
	// Bot users are denoted by their parent resource type.
	// The following bot types are available:
	//   * rule: acting on behalf of a Rule, author of comments and drafts
	//   * macro: acting on behalf of a Macro, author of comments and drafts
	//   * API: acting on behalf of OAuth clients
	//   * integration: acting on behalf of an Integration
	//   * CSAT: used for authoring CSAT response comments
	Type TeammateResponseType `json:"type"`

	// Username Username of the teammate (used for "@" mentions)
	Username string `json:"username"`
}

// TeammateResponseType Type of the teammate, normal teammates are denoted as "user", while visitors are denoted as "visitor".
// Bot users are denoted by their parent resource type.
// The following bot types are available:
//   - rule: acting on behalf of a Rule, author of comments and drafts
//   - macro: acting on behalf of a Macro, author of comments and drafts
//   - API: acting on behalf of OAuth clients
//   - integration: acting on behalf of an Integration
//   - CSAT: used for authoring CSAT response comments
type TeammateResponseType string

// Limit defines model for limit.
type Limit = int

// PageToken defines model for pageToken.
type PageToken = string

// SortByConversationMessages defines model for sortByConversationMessages.
type SortByConversationMessages = string

// SortOrder defines model for sortOrder.
type SortOrder string

// Conversation defines model for conversation.
type Conversation = ConversationResponse

// ListOfConversationSearchResults defines model for listOfConversationSearchResults.
type ListOfConversationSearchResults struct {
	UnderscoreLinks *struct {
		// Self Link to resource
		Self *string `json:"self,omitempty"`
	} `json:"_links,omitempty"`
	UnderscorePagination *struct {
		// Next Link to next [page of results](https://dev.frontapp.com/docs/pagination)
		Next *string `json:"next,omitempty"`
	} `json:"_pagination,omitempty"`
	UnderscoreResults *[]ConversationResponse `json:"_results,omitempty"`

	// UnderscoreTotal Total number of matching conversations
	UnderscoreTotal *int `json:"_total,omitempty"`
}

// ListOfInboxes defines model for listOfInboxes.
type ListOfInboxes struct {
	UnderscoreLinks *struct {
		// Self Link to resource
		Self *string `json:"self,omitempty"`
	} `json:"_links,omitempty"`
	UnderscoreResults *[]InboxResponse `json:"_results,omitempty"`
}

// ListOfMessages defines model for listOfMessages.
type ListOfMessages struct {
	UnderscoreLinks *struct {
		// Self Link to resource
		Self *string `json:"self,omitempty"`
	} `json:"_links,omitempty"`
	UnderscorePagination *struct {
		// Next Link to next [page of results](https://dev.frontapp.com/docs/pagination)
		Next *string `json:"next,omitempty"`
	} `json:"_pagination,omitempty"`
	UnderscoreResults *[]MessageResponse `json:"_results,omitempty"`
}

// SearchConversationsParams defines parameters for SearchConversations.
type SearchConversationsParams struct {
	// Limit Max number of results per [page](https://dev.frontapp.com/docs/pagination)
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// PageToken Token to use to request the [next page](https://dev.frontapp.com/docs/pagination)
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListConversationMessagesParams defines parameters for ListConversationMessages.
type ListConversationMessagesParams struct {
	// Limit Max number of results per [page](https://dev.frontapp.com/docs/pagination)
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// PageToken Token to use to request the [next page](https://dev.frontapp.com/docs/pagination)
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`

	// SortBy Field used to sort the messages. Only supports `created_at`.
	SortBy *SortByConversationMessages `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortOrder Order by which results should be sorted
	SortOrder *ListConversationMessagesParamsSortOrder `form:"sort_order,omitempty" json:"sort_order,omitempty"`
}

// ListConversationMessagesParamsSortOrder defines parameters for ListConversationMessages.
type ListConversationMessagesParamsSortOrder string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// SearchConversations request
	SearchConversations(ctx context.Context, query string, params *SearchConversationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetConversationById request
	GetConversationById(ctx context.Context, conversationId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListConversationMessages request
	ListConversationMessages(ctx context.Context, conversationId string, params *ListConversationMessagesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListInboxes request
	ListInboxes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListTeammateInboxes request
	ListTeammateInboxes(ctx context.Context, teammateId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) SearchConversations(ctx context.Context, query string, params *SearchConversationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchConversationsRequest(c.Server, query, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetConversationById(ctx context.Context, conversationId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConversationByIdRequest(c.Server, conversationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListConversationMessages(ctx context.Context, conversationId string, params *ListConversationMessagesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListConversationMessagesRequest(c.Server, conversationId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListInboxes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListInboxesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListTeammateInboxes(ctx context.Context, teammateId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListTeammateInboxesRequest(c.Server, teammateId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSearchConversationsRequest generates requests for SearchConversations
func NewSearchConversationsRequest(server string, query string, params *SearchConversationsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "query", query, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conversations/search/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageToken != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_token", *params.PageToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetConversationByIdRequest generates requests for GetConversationById
func NewGetConversationByIdRequest(server string, conversationId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "conversation_id", conversationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conversations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListConversationMessagesRequest generates requests for ListConversationMessages
func NewListConversationMessagesRequest(server string, conversationId string, params *ListConversationMessagesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "conversation_id", conversationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conversations/%s/messages", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageToken != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_token", *params.PageToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SortBy != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort_by", *params.SortBy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SortOrder != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort_order", *params.SortOrder, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListInboxesRequest generates requests for ListInboxes
func NewListInboxesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/inboxes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListTeammateInboxesRequest generates requests for ListTeammateInboxes
func NewListTeammateInboxesRequest(server string, teammateId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "teammate_id", teammateId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/teammates/%s/inboxes", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SearchConversationsWithResponse request
	SearchConversationsWithResponse(ctx context.Context, query string, params *SearchConversationsParams, reqEditors ...RequestEditorFn) (*SearchConversationsResponse, error)

	// GetConversationByIdWithResponse request
	GetConversationByIdWithResponse(ctx context.Context, conversationId string, reqEditors ...RequestEditorFn) (*GetConversationByIdResponse, error)

	// ListConversationMessagesWithResponse request
	ListConversationMessagesWithResponse(ctx context.Context, conversationId string, params *ListConversationMessagesParams, reqEditors ...RequestEditorFn) (*ListConversationMessagesResponse, error)

	// ListInboxesWithResponse request
	ListInboxesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListInboxesResponse, error)

	// ListTeammateInboxesWithResponse request
	ListTeammateInboxesWithResponse(ctx context.Context, teammateId string, reqEditors ...RequestEditorFn) (*ListTeammateInboxesResponse, error)
}

type SearchConversationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListOfConversationSearchResults
}

// Status returns HTTPResponse.Status
func (r SearchConversationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchConversationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetConversationByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Conversation
}

// Status returns HTTPResponse.Status
func (r GetConversationByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConversationByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListConversationMessagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListOfMessages
}

// Status returns HTTPResponse.Status
func (r ListConversationMessagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListConversationMessagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListInboxesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListOfInboxes
}

// Status returns HTTPResponse.Status
func (r ListInboxesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListInboxesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListTeammateInboxesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListOfInboxes
}

// Status returns HTTPResponse.Status
func (r ListTeammateInboxesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListTeammateInboxesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// SearchConversationsWithResponse request returning *SearchConversationsResponse
func (c *ClientWithResponses) SearchConversationsWithResponse(ctx context.Context, query string, params *SearchConversationsParams, reqEditors ...RequestEditorFn) (*SearchConversationsResponse, error) {
	rsp, err := c.SearchConversations(ctx, query, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchConversationsResponse(rsp)
}

// GetConversationByIdWithResponse request returning *GetConversationByIdResponse
func (c *ClientWithResponses) GetConversationByIdWithResponse(ctx context.Context, conversationId string, reqEditors ...RequestEditorFn) (*GetConversationByIdResponse, error) {
	rsp, err := c.GetConversationById(ctx, conversationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConversationByIdResponse(rsp)
}

// ListConversationMessagesWithResponse request returning *ListConversationMessagesResponse
func (c *ClientWithResponses) ListConversationMessagesWithResponse(ctx context.Context, conversationId string, params *ListConversationMessagesParams, reqEditors ...RequestEditorFn) (*ListConversationMessagesResponse, error) {
	rsp, err := c.ListConversationMessages(ctx, conversationId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListConversationMessagesResponse(rsp)
}

// ListInboxesWithResponse request returning *ListInboxesResponse
func (c *ClientWithResponses) ListInboxesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListInboxesResponse, error) {
	rsp, err := c.ListInboxes(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListInboxesResponse(rsp)
}

// ListTeammateInboxesWithResponse request returning *ListTeammateInboxesResponse
func (c *ClientWithResponses) ListTeammateInboxesWithResponse(ctx context.Context, teammateId string, reqEditors ...RequestEditorFn) (*ListTeammateInboxesResponse, error) {
	rsp, err := c.ListTeammateInboxes(ctx, teammateId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListTeammateInboxesResponse(rsp)
}

// ParseSearchConversationsResponse parses an HTTP response from a SearchConversationsWithResponse call
func ParseSearchConversationsResponse(rsp *http.Response) (*SearchConversationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchConversationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListOfConversationSearchResults
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetConversationByIdResponse parses an HTTP response from a GetConversationByIdWithResponse call
func ParseGetConversationByIdResponse(rsp *http.Response) (*GetConversationByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConversationByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Conversation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListConversationMessagesResponse parses an HTTP response from a ListConversationMessagesWithResponse call
func ParseListConversationMessagesResponse(rsp *http.Response) (*ListConversationMessagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListConversationMessagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListOfMessages
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListInboxesResponse parses an HTTP response from a ListInboxesWithResponse call
func ParseListInboxesResponse(rsp *http.Response) (*ListInboxesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListInboxesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListOfInboxes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListTeammateInboxesResponse parses an HTTP response from a ListTeammateInboxesWithResponse call
func ParseListTeammateInboxesResponse(rsp *http.Response) (*ListTeammateInboxesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListTeammateInboxesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListOfInboxes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
